# Gradle
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric
minecraft_version=1.21.1
yarn_mappings=1.21.1+build.3
loader_version=0.16.9

# Fabric API
fabric_version=0.110.5+1.21.1

# Kotlin
kotlin_version=2.0.21
fabric_kotlin_version=1.12.3+kotlin.2.0.21

# Mod
mod_version=1.0.0
maven_group=com.pokemon.catchcombo
archives_base_name=cobblecatchcombo

# Cobblemon
cobblemon_version=1.7.1+1.21.1

# Text Placeholder API
placeholder_api_version=2.4.2+1.21
